"""
AhuraInk Gallery Data Generator
Run by GitHub Actions whenever images are pushed to gallery/
Scans gallery/ filenames → writes gallery-data.js

Filename format: NNN INIT1 - INIT2.jpg
  NNN   = zero-padded number (e.g. 001, 023)
  INITs = category initials separated by " - "

Category initials:
  R  → realistic     MR → microreal    GW → graywash
  CA → colorart      FL → fineline     BG → blackgray
  DW → dotwork       CU → coverup      M  → mandala
"""

import os, re, json
from urllib.parse import quote

INITIALS = {
    'R':  'realistic',
    'MR': 'microreal',
    'GW': 'graywash',
    'CA': 'colorart',
    'FL': 'fineline',
    'BG': 'blackgray',
    'DW': 'dotwork',
    'CU': 'coverup',
    'M':  'mandala',
    'MD': 'mandala',
}

GALLERY_DIR = 'gallery'
items = []

for filename in sorted(os.listdir(GALLERY_DIR)):
    if not re.search(r'\.(jpg|jpeg|png|webp)$', filename, re.I):
        continue

    stem = os.path.splitext(filename)[0].strip()  # "001 MR" or "009 R - GW"
    parts = stem.split(' ', 1)                     # ["001", "MR"] or ["009", "R - GW"]
    if not parts:
        continue

    item_id = parts[0]
    if not re.match(r'^\d+$', item_id):
        continue  # skip non-standard filenames

    raw_inits = parts[1].strip() if len(parts) > 1 else ''
    initials  = [i.strip() for i in raw_inits.split('-') if i.strip()]
    cats      = [INITIALS[i.upper()] for i in initials if i.upper() in INITIALS]

    if not cats:
        cats = ['realistic']  # fallback

    src = 'gallery/' + quote(filename)
    items.append({'id': item_id, 'cats': cats, 'src': src})

lines = [
    '// Auto-generated by GitHub Actions — do not edit manually.',
    '// Push photos to gallery/ and this file updates automatically.',
    'const GALLERY_DATA = [',
]
for item in items:
    lines.append(f'  {{ id: "{item["id"]}", cats: {json.dumps(item["cats"])}, src: "{item["src"]}" }},')
lines.append('];')

out = '\n'.join(lines) + '\n'
with open('gallery-data.js', 'w') as f:
    f.write(out)

print(f'✓ gallery-data.js written with {len(items)} photos')
